[book]
authors = ["Kyosuke Fujimoto"]
language = "en"
src = "src"
title = "STU"
description = "STU Documentation"

[output.html]
git-repository-url = "https://github.com/lusingander/stu"
site-url = "/stu/"
default-theme = "rust"
