name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      msrv: ${{ steps.get-msrv.outputs.msrv }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get MSRV
        id: get-msrv
        run: |
          MSRV=$(grep '^rust-version' Cargo.toml | cut -d '"' -f 2)
          echo "msrv=$MSRV" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    strategy:
      matrix:
        versions:
          - stable
          - ${{ needs.prepare.outputs.msrv }}
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          - os: macos-latest
            versions: ${{ needs.prepare.outputs.msrv }}
          - os: windows-latest
            versions: ${{ needs.prepare.outputs.msrv }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # latest commit as of 2026-03-28
        with:
          toolchain: ${{ matrix.versions }}
          components: rustfmt, clippy
      - name: Cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Version
        run: |
          rustc --version
          cargo --version
          cargo fmt -- --version
          cargo clippy -- --version
      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo test --verbose
